ticketee/config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "base#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all

  validates :name, presence: true
end

ticketee/app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

ticketee/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"
  
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

ticketee/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

ticketee/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authorize_admin!

  def index

  end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
end

ticketee/app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController

  before_action :set_project, only: [:destroy]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created."
      render "new"
    end
  end


  def destroy
    @project.destroy

    flash[:notice] = "Project has been deleted"

    redirect_to projects_path
  end


  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end

end

ticketee/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def show

  end

  def update
    # remove password field if empty
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been updated."
      render "edit"
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User was deleted successfully."
    end

    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

ticketee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private

  def not_authorized
    redirect_to root_path, alert: "You are not allowed to do that."
  end
end

ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = policy_scope(Project)

  end


  def show
    authorize @project, :show?
  end

  def edit
  end

  def update

    if @project.update(project_params)
      flash[:notice] = 'Project has been updated'
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been updated"
      render "edit"
    end

  end


  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end


  def project_params
    params.require(:project).permit(:name, :description)
  end
end

ticketee/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def show
  end

  def edit

  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."

    redirect_to @project
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :description)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end
end

ticketee/app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

ticketee/app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

ticketee/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

ticketee/app/helpers/application_helper.rb
module ApplicationHelper

  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end

  def admins_only(&block)

    block.call if current_user.try(:admin)
  end
end

ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

ticketee/app/helpers/tickets_helper.rb
module TicketsHelper
end

ticketee/app/views/admin/base/index.html.erb
<div class="row">
  <div class="col-md-8">
    <header>
      <h1>Admin Lounge</h1>
    </header>
    <p>Welcome to Ticketee's Admin Lounge. Please enjoy your stay.</p>
  </div>

  <div class="col-md-4">
  <h2>Admin Links</h2>
    <ul class="nav nav-stacked">
      <li><%= link_to "Users", admin_users_path %></li>
    </ul>
  </div>
</div>

ticketee/app/views/admin/projects/_form.html.erb
<%= simple_form_for [:admin, project] do |f| %>

    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit, class: 'btn btn-info' %>
<% end %>

ticketee/app/views/admin/projects/new.html.erb
<div class="page-header">
    <h2>Add a Project</h2>
</div>

<%= render 'form', project: @project %>

ticketee/app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :admin, label: "Is an admin?" %>
    <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

ticketee/app/views/admin/users/edit.html.erb
<div class="page-header">
  <h2>Edit User</h2>

</div>

<%= render "form", user: @user %>

ticketee/app/views/admin/users/index.html.erb
<div class="page-header">
      <%= link_to "New User", new_admin_user_path, class: "new pull-right" %>

  <h2>Users</h2>

</div>

<div id="users">

<table class="table table-striped table-bordered table-responsive table-hover">
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user, [:admin, user] %></td>
    </tr>
  <% end %>
</table>

</div>

ticketee/app/views/admin/users/new.html.erb
<div class="page-header">
  <h2>Users</h2>

</div>

<%= render "form", user: @user %>

ticketee/app/views/admin/users/show.html.erb
<div class="page-header">
  <%= link_to "Edit User", [:edit, :admin, @user], class: "edit pull-right" %>
  <%= link_to "Delete User", [:admin, @user], method: :delete, class: "delete pull-right", data: { confirm: "Are you sure you want to delete this User?"} %>

  <h2><%= @user.email %></h2>

</div>

<div id="user">

</div>

ticketee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
        <%= yield(:title) %>
    <% else %>
        Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= render "partials/navbar" %>

<% flash.each do |key, message| %>
    <div class="alert alert-<%= key %>">
      <%= message %>
    </div>
<% end %>

<%= yield %>

</div>

</body>
</html>

ticketee/app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Ticketee</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/projects">Projects <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
            <% admins_only do %>
                <li><%= link_to "Admin", admin_root_path %></li>
            <% end %>
            <li><%= link_to "Signed in as " + current_user.email, destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li<%= " class='active'".html_safe if current_page?("/users/sign_up") %>>
              <%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

ticketee/app/views/projects/_form.html.erb
<%= simple_form_for project do |f| %>

    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit, class: 'btn btn-info' %>
<% end %>

ticketee/app/views/projects/edit.html.erb
<h2 class="page-heading">Edit Project</h2>

<%= render 'form', project: @project %>

ticketee/app/views/projects/index.html.erb
<div class="page-header">
  <% admins_only do %>
      <%= link_to "New Project", new_admin_project_path, class: "new pull-right" %>
  <% end %>

  <h2>Projects</h2>

</div>

<div id="projects">

  <% @projects.each do |project| %>
    <h3><%= link_to project.name, project %></h3>
      <p><%= project.description %></p>
  <% end %>

</div>

ticketee/app/views/projects/show.html.erb
<% title(@project.name, 'Projects') %>


<div class="page-header">

  <div class="btn-group pull-right">

<%= link_to  "New Ticket", new_project_ticket_path(@project), class: "new" %>

<%= link_to  "Edit Project", edit_project_path(@project), class: "edit" %>

    <% admins_only do %>
<%= link_to "Delete Project",
            admin_project_path(@project),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this project?" },
            class: "delete"
    %>
    <% end %>
  </div>

<h2><%= @project.name %></h2>

</div>

<ul id="tickets">
  <% @project.tickets.each do |ticket| %>
    <li>#<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %></li>
  <% end %>
</ul>

ticketee/app/views/tickets/_form.html.erb
<%= simple_form_for [project, ticket] do |f| %>

    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.button :submit, class: 'btn-info' %>

<% end %>

ticketee/app/views/tickets/edit.html.erb
<div class="page-header">
  <h1>Edit Ticket
    <small><%= @project.name %></small></h1>

  <%= render "form", project: @project, ticket: @ticket %>
</div>

ticketee/app/views/tickets/new.html.erb
<div class="page-header">
  <h2>New Ticket
    <small><%= @project.name %></small></h2>
</div>

<%= render 'form', project: @project, ticket: @ticket %>

ticketee/app/views/tickets/show.html.erb
<div id="ticket">

  <div class="page-header">
    <h2><%= @project.name %></h2>
  </div>

  <div class="page-header">

    <div class="btn-group pull-right">
    <%= link_to "Edit Ticket", [:edit, @project, @ticket], class: "edit" %>
    <%= link_to "Delete Ticket",
                [@project, @ticket],
                method: :delete,
                data: { confirm: "Are you sure you want to delete this ticket?"},
                class: "delete" %>
    </div>

    <h3><%= @ticket.title %></h3>

  </div>

  <p id="author">Created by <%= @ticket.author.email %>, <%= time_ago_in_words(@ticket.created_at) %> ago</p>

    <%= simple_format(@ticket.description) %>

</div>